#!/bin/bash
set -e

# Log all output
exec > >(tee /var/log/user-data.log)
exec 2>&1

echo "========================================="
echo "SCIM Entitlements Demo - Server Setup"
echo "Repository: ${github_repo}"
echo "SCIM Path: ${scim_server_path}"
echo "Domain: ${domain_name}"
echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "========================================="

# Update system packages
echo "📦 Updating system packages..."
apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# Install Python and dependencies
echo "🐍 Installing Python and build tools..."
apt-get install -y python3 python3-pip git curl gpg

# Install Caddy for automatic HTTPS
echo "🔒 Installing Caddy web server..."
apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
apt-get update -y
apt-get install -y caddy

# Create application directory
echo "📁 Setting up application directory..."
mkdir -p /opt/scim-demo
cd /opt/scim-demo

# Download SCIM server application from GitHub
echo "⬇️  Downloading SCIM server from GitHub..."
echo "URL: https://raw.githubusercontent.com/${github_repo}/${scim_server_path}/demo_scim_server.py"

# Download main application
curl -fSL -o demo_scim_server.py "https://raw.githubusercontent.com/${github_repo}/${scim_server_path}/demo_scim_server.py" || {
  echo "❌ Failed to download SCIM server application!"
  echo "Trying alternative method (git clone)..."
  git clone "https://github.com/${github_repo}.git" temp_repo
  # Extract just the path we need
  SCIM_PATH_CLEAN=$(echo "${scim_server_path}" | sed 's|^main/||')
  cp "temp_repo/$SCIM_PATH_CLEAN/demo_scim_server.py" . || {
    echo "❌ Failed to find SCIM server in repository!"
    exit 1
  }
  rm -rf temp_repo
}

# Download requirements.txt
echo "⬇️  Downloading requirements.txt..."
curl -fSL -o requirements.txt "https://raw.githubusercontent.com/${github_repo}/${scim_server_path}/requirements.txt" || {
  echo "⚠️  No requirements.txt found, creating default..."
  cat > requirements.txt <<EOF
Flask==3.0.0
python-dotenv==1.0.0
EOF
}

# Download entitlements configuration
echo "⬇️  Downloading entitlements configuration..."
ENTITLEMENTS_SOURCE="${entitlements_file}"
if [ -z "$ENTITLEMENTS_SOURCE" ]; then
  ENTITLEMENTS_SOURCE="entitlements.json"
fi

echo "   Entitlements file: $ENTITLEMENTS_SOURCE"

# Try to download the specified entitlements file
curl -fSL -o entitlements.json "https://raw.githubusercontent.com/${github_repo}/${scim_server_path}/$ENTITLEMENTS_SOURCE" || {
  echo "⚠️  Could not download entitlements from: $ENTITLEMENTS_SOURCE"
  echo "   Server will use built-in default entitlements"
  # Create empty file so the script doesn't fail
  touch entitlements.json
}

if [ -f entitlements.json ] && [ -s entitlements.json ]; then
  echo "✅ Entitlements configuration downloaded successfully"
  # Display entitlements summary
  ENTITLEMENTS_COUNT=$(python3 -c "import json; print(len(json.load(open('entitlements.json'))['entitlements']))" 2>/dev/null || echo "unknown")
  echo "   Entitlements loaded: $ENTITLEMENTS_COUNT"
else
  echo "⚠️  Entitlements file is empty, server will use defaults"
fi

# Verify SCIM server downloaded successfully
if [ ! -f demo_scim_server.py ] || [ ! -s demo_scim_server.py ]; then
  echo "❌ SCIM server file is missing or empty!"
  exit 1
fi

echo "✅ SCIM server downloaded successfully ($(wc -l < demo_scim_server.py) lines)"

# Install Python dependencies
echo "📚 Installing Python dependencies..."
pip3 install -r requirements.txt

# Create .env file for the application
echo "📝 Creating /opt/scim-demo/.env..."
cat > /opt/scim-demo/.env <<EOF
# Generated by user-data on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SCIM_AUTH_TOKEN=${scim_auth_token}
SCIM_BASIC_USER=${scim_basic_user}
SCIM_BASIC_PASS=${scim_basic_pass}
DOMAIN_NAME=${domain_name}
PYTHONUNBUFFERED=1
PORT=5000
%{ if custom_entitlements != "" ~}
CUSTOM_ENTITLEMENTS=${custom_entitlements}
%{ endif ~}
EOF
chmod 600 /opt/scim-demo/.env
chown root:root /opt/scim-demo/.env

echo "✅ Environment configuration created"

# Create systemd service for SCIM server
echo "⚙️  Creating systemd service..."
cat > /etc/systemd/system/scim-demo.service <<EOF
[Unit]
Description=SCIM Entitlements Demo Server
Documentation=https://github.com/${github_repo}
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/scim-demo
# Read environment from .env file
EnvironmentFile=-/opt/scim-demo/.env
Environment="PYTHONUNBUFFERED=1"
ExecStart=/bin/bash -lc "set -a; . /opt/scim-demo/.env; set +a; exec /usr/bin/python3 /opt/scim-demo/demo_scim_server.py"
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

# Security hardening
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

# Start and enable SCIM service
echo "🚀 Starting SCIM service..."
systemctl daemon-reload
systemctl enable scim-demo
systemctl start scim-demo

# Wait for service to start
sleep 5

# Check if service is running
if systemctl is-active --quiet scim-demo; then
  echo "✅ SCIM service started successfully"
  systemctl status scim-demo --no-pager | head -n 10
else
  echo "❌ SCIM service failed to start"
  echo "Last 50 lines from journal:"
  journalctl -u scim-demo -n 50
  exit 1
fi

# Configure Caddy for automatic HTTPS
echo "🔒 Configuring Caddy for HTTPS..."
cat > /etc/caddy/Caddyfile << 'CADDYEOF'
${domain_name} {
    reverse_proxy localhost:5000

    log {
        output file /var/log/caddy/access.log
        format json
    }

    encode gzip

    # Security headers
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
        Referrer-Policy "no-referrer-when-downgrade"
        X-XSS-Protection "1; mode=block"
    }

    # Health check endpoint (no auth required)
    handle /health {
        reverse_proxy localhost:5000
    }

    # All other endpoints
    handle {
        reverse_proxy localhost:5000
    }
}
CADDYEOF

# Create Caddy log directory
mkdir -p /var/log/caddy
chown caddy:caddy /var/log/caddy

# Restart Caddy to apply configuration
echo "🔄 Restarting Caddy..."
systemctl restart caddy

# Wait for Caddy to start
sleep 3

# Verify Caddy is running
if systemctl is-active --quiet caddy; then
  echo "✅ Caddy started successfully"
  systemctl status caddy --no-pager | head -n 10
else
  echo "❌ Caddy failed to start"
  echo "Last 50 lines from journal:"
  journalctl -u caddy -n 50
  exit 1
fi

# Create a status check script
cat > /usr/local/bin/scim-status << 'STATUSEOF'
#!/bin/bash
echo "==================================="
echo "SCIM Demo Server Status"
echo "==================================="
echo ""
echo "📊 SCIM Service:"
systemctl status scim-demo --no-pager | head -n 10
echo ""
echo "🔒 Caddy Service:"
systemctl status caddy --no-pager | head -n 10
echo ""
echo "🌐 Environment Variables:"
echo "  (Loaded from /opt/scim-demo/.env)"
systemctl show scim-demo -p Environment --no-pager
echo ""
echo "🏥 Local Health Check:"
curl -s http://localhost:5000/health | python3 -m json.tool 2>/dev/null || echo "Service not responding"
echo ""
echo "📝 Recent SCIM Logs:"
journalctl -u scim-demo -n 20 --no-pager
echo ""
echo "==================================="
STATUSEOF
chmod +x /usr/local/bin/scim-status

# Create a quick log viewer
cat > /usr/local/bin/scim-logs << 'LOGSEOF'
#!/bin/bash
echo "SCIM Demo Server Logs (Ctrl+C to exit)"
echo "======================================="
journalctl -u scim-demo -f
LOGSEOF
chmod +x /usr/local/bin/scim-logs

# Final health check with retries
echo "🏥 Running health check..."
sleep 10
HEALTH_OK=false
for i in {1..10}; do
  if curl -s http://localhost:5000/health > /dev/null 2>&1; then
    echo "✅ Health check passed on attempt $i!"
    HEALTH_OK=true
    break
  else
    echo "⏳ Attempt $i/10: Waiting for service to be ready..."
    sleep 5
  fi
done

if [ "$HEALTH_OK" = false ]; then
  echo "❌ Health check failed after 10 attempts"
  echo "Check logs with: journalctl -u scim-demo -n 100"
  exit 1
fi

# Display final status
echo ""
echo "========================================="
echo "✅ SCIM Demo Server Setup Complete!"
echo "========================================="
echo ""
echo "🌐 Domain: ${domain_name}"
echo "📊 Dashboard: https://${domain_name}"
echo "🔌 SCIM API: https://${domain_name}/scim/v2"
echo "🏥 Health: https://${domain_name}/health"
echo ""
echo "📝 Management Commands:"
echo "  - scim-status    # Check server status"
echo "  - scim-logs      # View live logs"
echo "  - systemctl restart scim-demo  # Restart SCIM service"
echo "  - systemctl restart caddy      # Restart Caddy"
echo ""
echo "📄 Log Files:"
echo "  - Setup: /var/log/user-data.log"
echo "  - SCIM: journalctl -u scim-demo"
echo "  - Caddy: /var/log/caddy/access.log"
echo ""
echo "⏱️  Note: Caddy may take a few minutes to provision"
echo "   the Let's Encrypt SSL certificate on first run."
echo "========================================="
