-- ==============================================================================
-- FULL PROFILE MIGRATION - VITA IGA DEMO USE CASES
-- ==============================================================================
-- Idempotent. Adds full Okta-profile columns to users and seeds the named
-- use-case users + supporting cast across the 3 demo agencies (Health,
-- Transportation, Social Services). Safe to re-run. Run AFTER schema.sql.
-- ==============================================================================

-- 1. Add full-profile columns (additive)
ALTER TABLE users ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS nick_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS primary_phone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS second_email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS street_address VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS country_code VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS user_type VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS cost_center VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS organization VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS division VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS agency_name VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS start_date VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS employment_type VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS employee_id VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS contractor_sponsor VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS contractor_start_date VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS contractor_end_date VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_health_employee BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_transportation_employee BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS health_email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS transportation_email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS department_assignments TEXT;

-- 2. Seed demo users (named + supporting). Existing rows untouched.
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP201145', 'mtorres', 'michael.torres@vdh.virginia.gov', 'Michael', 'Torres', 'Michael Torres', NULL, NULL, 'Budget Office', 'Budget Manager', NULL, '201145', '804-555-0148', '804-864-7001', NULL, '109 Governor St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDH-BUD-3001', 'Commonwealth of Virginia', 'Department of Health', 'Department of Health', '2014-03-17', 'Employee', '201145', NULL, NULL, NULL, TRUE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP248731', 'jrodriguez', 'jane.rodriguez@vdh.virginia.gov', 'Jane', 'Rodriguez', 'Jane Rodriguez', NULL, NULL, 'Budget Office', 'Budget Analyst', 'EMP201145', '248731', '804-555-0192', '804-864-7042', NULL, '109 Governor St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDH-BUD-3001', 'Commonwealth of Virginia', 'Department of Health', 'Department of Health', '2026-05-26', 'Employee', '248731', NULL, NULL, NULL, TRUE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP197834', 'rwilliams', 'robert.williams@vdh.virginia.gov', 'Robert', 'Williams', 'Robert Williams', NULL, NULL, 'Information Technology', 'Systems Administrator', 'EMP188220', '197834', '804-555-0177', '804-864-7110', NULL, '109 Governor St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDH-IT-2200', 'Commonwealth of Virginia', 'Department of Health', 'Department of Health', '2011-09-06', 'Employee', '197834', NULL, NULL, NULL, TRUE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP233401', 'jsmith.health', 'john.smith@vdh.virginia.gov', 'John', 'Smith', 'John Smith', NULL, NULL, 'Health Programs', 'Health Program Specialist', NULL, '233401', '804-555-0210', '804-864-7233', NULL, '109 Governor St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDH-HP-4100', 'Commonwealth of Virginia', 'Department of Health', 'Department of Health', '2019-01-14', 'Employee', '233401', NULL, NULL, NULL, TRUE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP240118', 'pnguyen', 'patricia.nguyen@vdh.virginia.gov', 'Patricia', 'Nguyen', 'Patricia Nguyen', NULL, NULL, 'Budget Office', 'Budget Analyst', 'EMP201145', '240118', '804-555-0233', '804-864-7044', NULL, '109 Governor St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDH-BUD-3001', 'Commonwealth of Virginia', 'Department of Health', 'Department of Health', '2021-06-28', 'Employee', '240118', NULL, NULL, NULL, TRUE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP188220', 'kdiaz', 'karen.diaz@vdh.virginia.gov', 'Karen', 'Diaz', 'Karen Diaz', NULL, NULL, 'Information Technology', 'IT Administrator', NULL, '188220', '804-555-0260', '804-864-7100', NULL, '109 Governor St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDH-IT-2200', 'Commonwealth of Virginia', 'Department of Health', 'Department of Health', '2009-11-02', 'Employee', '188220', NULL, NULL, NULL, TRUE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP251002', 'skim', 'sarah.kim@vdot.virginia.gov', 'Sarah', 'Kim', 'Sarah Kim', NULL, NULL, 'Transportation Planning', 'Transportation Planner', 'EMP209876', '251002', '804-555-0301', '804-786-2001', NULL, '1401 E Broad St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDOT-PLN-5300', 'Commonwealth of Virginia', 'Department of Transportation', 'Department of Transportation', '2022-08-15', 'Employee', '251002', NULL, NULL, NULL, FALSE, TRUE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP209876', 'jcoleman', 'james.coleman@vdot.virginia.gov', 'James', 'Coleman', 'James Coleman', NULL, NULL, 'District Engineering', 'District Engineering Manager', NULL, '209876', '804-555-0318', '804-786-2100', NULL, '1401 E Broad St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDOT-ENG-5100', 'Commonwealth of Virginia', 'Department of Transportation', 'Department of Transportation', '2015-04-20', 'Employee', '209876', NULL, NULL, NULL, FALSE, TRUE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('CTR300455', 'dchen', 'david.chen@vdot.virginia.gov', 'David', 'Chen', 'David Chen (Contractor)', NULL, NULL, 'Bridge Inspection', 'Bridge Inspection Consultant', 'EMP209876', NULL, '804-555-0345', NULL, NULL, '1401 E Broad St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDOT-ENG-5100', 'Commonwealth of Virginia', 'Department of Transportation', 'Department of Transportation', NULL, 'Employee', NULL, 'James Coleman', '2026-06-01', '2026-11-30', FALSE, TRUE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP262200', 'jsmith.transportation', 'john.smith@vdot.virginia.gov', 'John', 'Smith', 'John Smith', NULL, NULL, 'Highway Engineering', 'Highway Engineer', 'EMP209876', '262200', '804-555-0362', '804-786-2233', NULL, '1401 E Broad St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDOT-ENG-5100', 'Commonwealth of Virginia', 'Department of Transportation', 'Department of Transportation', '2018-10-08', 'Employee', '262200', NULL, NULL, NULL, FALSE, TRUE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP215543', 'abrooks', 'angela.brooks@dss.virginia.gov', 'Angela', 'Brooks', 'Angela Brooks', NULL, NULL, 'Information Technology', 'IT Administrator', NULL, '215543', '804-555-0401', '804-726-7001', NULL, '801 E Main St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDSS-IT-2200', 'Commonwealth of Virginia', 'Department of Social Services', 'Department of Social Services', '2016-02-22', 'Employee', '215543', NULL, NULL, NULL, FALSE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP230711', 'mbell', 'marcus.bell@dss.virginia.gov', 'Marcus', 'Bell', 'Marcus Bell', NULL, NULL, 'Benefits Programs', 'Benefits Programs Specialist', 'EMP215543', '230711', '804-555-0420', '804-726-7150', NULL, '801 E Main St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDSS-BP-6100', 'Commonwealth of Virginia', 'Department of Social Services', 'Department of Social Services', '2020-03-09', 'Employee', '230711', NULL, NULL, NULL, FALSE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('EMP244900', 'lpark', 'lisa.park@vdh.virginia.gov', 'Lisa', 'Park', 'Lisa Park', NULL, NULL, 'Data & Analytics', 'Data Analyst', 'EMP201145', '244900', '804-555-0455', '804-864-7300', NULL, '109 Governor St', 'Richmond', 'VA', '23219', 'US', 'Employee', 'VDH-DA-3500', 'Commonwealth of Virginia', 'Department of Health', 'Department of Health', '2021-11-15', 'Employee', '244900', NULL, NULL, NULL, TRUE, TRUE, 'lisa.park@vdh.virginia.gov', 'lisa.park@vdot.virginia.gov', '["Department of Health","Department of Transportation"]', 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;
INSERT INTO users (user_id, username, email, first_name, last_name, display_name, middle_name, nick_name, department, title, manager_id, employee_number, mobile_phone, primary_phone, second_email, street_address, city, state, zip_code, country_code, user_type, cost_center, organization, division, agency_name, start_date, employment_type, employee_id, contractor_sponsor, contractor_start_date, contractor_end_date, is_health_employee, is_transportation_employee, health_email, transportation_email, department_assignments, status)
  VALUES ('SVC900001', 'svc-cardinal-sync', 'svc-cardinal-sync@vita.virginia.gov', 'Cardinal', 'Sync Service', 'svc-cardinal-sync', NULL, NULL, 'Identity Services', 'Service Account', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'US', 'Employee', 'VITA-IDS-1000', 'Commonwealth of Virginia', 'Virginia Information Technologies Agency', 'VITA', NULL, 'Employee', NULL, 'VITA Identity Services', NULL, NULL, FALSE, FALSE, NULL, NULL, NULL, 'ACTIVE')
  ON CONFLICT (user_id) DO NOTHING;

-- 3. A few Day-1 entitlement grants for the budget analysts / managers
INSERT INTO user_entitlements (user_id, entitlement_id, granted_by) VALUES ('EMP248731','ent-reporting','system') ON CONFLICT (user_id, entitlement_id) DO NOTHING;
INSERT INTO user_entitlements (user_id, entitlement_id, granted_by) VALUES ('EMP248731','ent-hr-employee','system') ON CONFLICT (user_id, entitlement_id) DO NOTHING;
INSERT INTO user_entitlements (user_id, entitlement_id, granted_by) VALUES ('EMP240118','ent-reporting','system') ON CONFLICT (user_id, entitlement_id) DO NOTHING;
INSERT INTO user_entitlements (user_id, entitlement_id, granted_by) VALUES ('EMP240118','ent-hr-employee','system') ON CONFLICT (user_id, entitlement_id) DO NOTHING;
INSERT INTO user_entitlements (user_id, entitlement_id, granted_by) VALUES ('EMP201145','ent-hr-manager','system') ON CONFLICT (user_id, entitlement_id) DO NOTHING;
INSERT INTO user_entitlements (user_id, entitlement_id, granted_by) VALUES ('EMP201145','ent-reporting','system') ON CONFLICT (user_id, entitlement_id) DO NOTHING;
INSERT INTO user_entitlements (user_id, entitlement_id, granted_by) VALUES ('EMP244900','ent-reporting','system') ON CONFLICT (user_id, entitlement_id) DO NOTHING;
